# Generated by Django 4.1.7 on 2023-02-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_weightlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightlog',
            name='date',
            field=models.DateField(),
        ),
    ]
